### ISSUE TITLE
Hình ảnh 2

### ISSUE THREAD

**Issue by NguyenDacTien2003** [TuanNgoc16/Exam_Ejb_Employee#2]

**Comment by NguyenDacTien2003** [comment]
![image](https://github.com/TuanNgoc16/Exam_Ejb_Employee/assets/103101867/a8f317c5-74ae-4f23-a90b-5e64b128c22b)

**Comment by TuanNgoc16** [comment]
Hình ảnh 2

![image](https://github.com/TuanNgoc16/Exam_Ejb_Employee/assets/103101440/52a43012-f45f-4ee3-a89e-ac90a4f5c1dd)
